# Copyright (c) 2021, NVIDIA CORPORATION.

[build-system]

requires = [
    "wheel",
    "setuptools",
    "numpy",
    "pandas>=1.0,<1.3.0dev0",
    "cython>=0.29,<0.30",
    "typing_extensions",
    "flatbuffers",
    "packaging",
    "protobuf",
    "nvtx>=0.2.1",
    "cachetools",
    "numba>=0.49.0,!=0.51.0"
]

[tool.black]
line-length = 79
target-version = ["py36"]
include = '\.py?$'
exclude = '''
/(
    thirdparty |
    \.eggs |
    \.git |
    \.hg |
    \.mypy_cache |
    \.tox |
    \.venv |
    _build |
    buck-out |
    build |
    dist
)/
'''
