name: Echo on PR

on:
  pull_request:
    types: [opened]
  push:

jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo abc
        run: echo 'abc'
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Generate text file
        run: |
          echo '{"context":"Pandas tests", "description":"90/100", "state":"success"}' > gh-status.json
          echo "### Hello world1! :rocket:" >> $GITHUB_STEP_SUMMARY
      - name: Upload file to GitHub Artifact1
        uses: actions/upload-artifact@v4
        with:
          name: gh-status
          path: gh-status.json
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: gh-status
          path: downloaded_artifacts/

# abc
