name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - checks
      - conda-cpp-build
      - conda-cpp-checks
      - conda-cpp-tests
      - conda-python-build
      - conda-python-cudf-tests
      - conda-python-other-tests
      - conda-java-tests
      - static-configure
      - conda-notebook-tests
      - docs-build
      - wheel-build-cudf
      - wheel-tests-cudf
      - wheel-build-dask-cudf
      - wheel-tests-dask-cudf
      - devcontainer
      - unit-tests-cudf-pandas
      - pandas-tests
      - pandas-tests-diff
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@branch-24.06
  checks:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/checks.yaml@branch-24.06
    with:
      enable_check_generated_files: false
  conda-cpp-build:
    needs: checks
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-cpp-build.yaml@branch-24.06
    with:
      build_type: pull-request
  conda-cpp-checks:
    needs: conda-cpp-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-cpp-post-build-checks.yaml@branch-24.06
    with:
      build_type: pull-request
      enable_check_symbols: true
  conda-cpp-tests:
    needs: conda-cpp-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-cpp-tests.yaml@branch-24.06
    with:
      build_type: pull-request
  conda-python-build:
    needs: conda-cpp-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-build.yaml@branch-24.06
    with:
      build_type: pull-request
  conda-python-cudf-tests:
    needs: conda-python-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-tests.yaml@branch-24.06
    with:
      build_type: pull-request
      script: "ci/test_python_cudf.sh"
  conda-python-other-tests:
    # Tests for dask_cudf, custreamz, cudf_kafka are separated for CI parallelism
    needs: conda-python-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-tests.yaml@branch-24.06
    with:
      build_type: pull-request
      script: "ci/test_python_other.sh"
  conda-java-tests:
    needs: conda-cpp-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@branch-24.06
    with:
      build_type: pull-request
      node_type: "gpu-v100-latest-1"
      arch: "amd64"
      container_image: "rapidsai/ci-conda:latest"
      run_script: "ci/test_java.sh"
  static-configure:
    needs: checks
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@branch-24.06
    with:
      build_type: pull-request
      # Use the wheel container so we can skip conda solves and since our
      # primary static consumers (Spark) are not in conda anyway.
      container_image: "rapidsai/ci-wheel:latest"
      run_script: "ci/configure_cpp_static.sh"
  conda-notebook-tests:
    needs: conda-python-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@branch-24.06
    with:
      build_type: pull-request
      node_type: "gpu-v100-latest-1"
      arch: "amd64"
      container_image: "rapidsai/ci-conda:latest"
      run_script: "ci/test_notebooks.sh"
  docs-build:
    needs: conda-python-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@branch-24.06
    with:
      build_type: pull-request
      node_type: "gpu-v100-latest-1"
      arch: "amd64"
      container_image: "rapidsai/ci-conda:latest"
      run_script: "ci/build_docs.sh"
  wheel-build-cudf:
    needs: checks
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.06
    with:
      build_type: pull-request
      script: "ci/build_wheel_cudf.sh"
  wheel-tests-cudf:
    needs: wheel-build-cudf
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@branch-24.06
    with:
      build_type: pull-request
      script: ci/test_wheel_cudf.sh
  wheel-build-dask-cudf:
    needs: wheel-build-cudf
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.06
    with:
      # This selects "ARCH=amd64 + the latest supported Python + CUDA".
      matrix_filter: map(select(.ARCH == "amd64")) | group_by(.CUDA_VER|split(".")|map(tonumber)|.[0]) | map(max_by([(.PY_VER|split(".")|map(tonumber)), (.CUDA_VER|split(".")|map(tonumber))]))
      build_type: pull-request
      script: "ci/build_wheel_dask_cudf.sh"
  wheel-tests-dask-cudf:
    needs: wheel-build-dask-cudf
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@branch-24.06
    with:
      # This selects "ARCH=amd64 + the latest supported Python + CUDA".
      matrix_filter: map(select(.ARCH == "amd64")) | group_by(.CUDA_VER|split(".")|map(tonumber)|.[0]) | map(max_by([(.PY_VER|split(".")|map(tonumber)), (.CUDA_VER|split(".")|map(tonumber))]))
      build_type: pull-request
      script: ci/test_wheel_dask_cudf.sh
  devcontainer:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/build-in-devcontainer.yaml@branch-24.06
    with:
      arch: '["amd64"]'
      cuda: '["12.2"]'
      build_command: |
        sccache -z;
        build-all -DBUILD_BENCHMARKS=ON --verbose;
        sccache -s;
  unit-tests-cudf-pandas:
    needs: wheel-build-cudf
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@branch-24.06
    with:
      matrix_filter: map(select(.ARCH == "amd64")) | group_by(.CUDA_VER|split(".")|map(tonumber)|.[0]) | map(max_by([(.PY_VER|split(".")|map(tonumber)), (.CUDA_VER|split(".")|map(tonumber))]))
      build_type: pull-request
      script: ci/cudf_pandas_scripts/run_tests.sh
  pandas-tests:
    # run the Pandas unit tests using PR branch
    needs: wheel-build-cudf
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@branch-24.06
    with:
      matrix_filter: map(select(.ARCH == "amd64")) | group_by(.CUDA_VER|split(".")|map(tonumber)|.[0]) | map(max_by([(.PY_VER|split(".")|map(tonumber)), (.CUDA_VER|split(".")|map(tonumber))]))
      build_type: pull-request
      script: ci/cudf_pandas_scripts/pandas-tests/run.sh pr
      # Hide test failures because they exceed the GITHUB_STEP_SUMMARY output limit.
      test_summary_show: "none"
  pandas-tests-diff:
    # diff the results of running the Pandas unit tests and publish a job summary
    needs: pandas-tests
    uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@patch-1
    with:
        node_type: cpu4
        build_type: pull-request
        run_script: ci/cudf_pandas_scripts/pandas-tests/diff.sh
  pandas-test-reporting:
    needs: pandas-tests-diff
    if: ${{ needs.pandas-tests-diff.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: gh-status
          path: downloaded_artifacts/
          # Assuming 'copy.yml' is the workflow filename that produced the artifact
          workflow: copy.yml
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Read artifact JSON
        id: read_artifact
        run: |
          CONTENT=$(cat downloaded_artifacts/gh-status.json)
          echo "::set-output name=content::$CONTENT"
      - name: Create status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACT_CONTENT: ${{ steps.read_artifact.outputs.content }}
          COMMIT_SHA: ${{ github.sha }}
          REPO_NAME: ${{ github.repository }}
        run: |
          # Assuming you have the job ID from somewhere or it's not needed anymore
          # If you still need to fetch the job ID, you would insert the logic here

          CONTENT_JSON=$(echo $ARTIFACT_CONTENT | jq .)
          CUSTOM_CONTEXT=$(echo $CONTENT_JSON | jq -r .context)
          CUSTOM_DESCRIPTION=$(echo $CONTENT_JSON | jq -r .description)
          CUSTOM_TARGET_URL=$(echo $CONTENT_JSON | jq -r .target_url)
          CUSTOM_STATE=$(echo $CONTENT_JSON | jq -r .state)

          # Use default values if any field is missing
          if [ -z "$CUSTOM_CONTEXT" ] || [ "$CUSTOM_CONTEXT" = "null" ]; then CUSTOM_CONTEXT="Custom CI Status Check"; fi
          if [ -z "$CUSTOM_DESCRIPTION" ] || [ "$CUSTOM_DESCRIPTION" = "null" ]; then CUSTOM_DESCRIPTION="Custom CI Status description"; fi
          if [ -z "$CUSTOM_TARGET_URL" ] || [ "$CUSTOM_TARGET_URL" = "null" ]; then CUSTOM_TARGET_URL="https://github.com/$REPO_NAME/commit/$COMMIT_SHA/checks"; fi
          if [ -z "$CUSTOM_STATE" ] || [ "$CUSTOM_STATE" = "null" ]; then CUSTOM_STATE="success"; fi

          echo "Job ID: $JOB_ID"
          echo $CUSTOM_CONTEXT
          echo $CUSTOM_DESCRIPTION
          echo $CUSTOM_TARGET_URL
          echo $CUSTOM_STATE

          # Create status
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO_NAME/statuses/$COMMIT_SHA" \
            -d "{\"state\":\"$CUSTOM_STATE\",\"target_url\":\"$CUSTOM_TARGET_URL\",\"description\":\"$CUSTOM_DESCRIPTION\",\"context\":\"$CUSTOM_CONTEXT\"}"
